[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trust_token = "3gUohiKvtQGZ2gXdimtvtVxy3JEFC9mTs3fLuo4ox5Ju"
reputation_card = "FmZBiFUHHtGQioU11V9asYiJGP5wDdrLqoikzAyEyRtc"

[programs.devnet]
trust_token = "3gUohiKvtQGZ2gXdimtvtVxy3JEFC9mTs3fLuo4ox5Ju"
reputation_card = "FmZBiFUHHtGQioU11V9asYiJGP5wDdrLqoikzAyEyRtc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
initialize = "yarn ts-node scripts/initialize.ts"
check-status = "yarn ts-node scripts/test_mint_raw.ts"
test-mint = "yarn ts-node scripts/mint_nft.ts"
